version: '3'
services:
  run:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5901:5901"
      - "6901:6901"
    environment:
      - SCRIPTNAME
      - VNC_PW=secret
    volumes:
      - ./reports:/seeny/build/libs/logs:rw
      - ./screens:/seeny/screens:rw
      - ./scripts:/seeny/build/libs/websites:rw

